Alpdk horizontal shooting
InnocentusLime/project-consequences pull request #63
Opened 2023-09-20 16:02 UTC by alpdk

Main idea, when player is moving he change his/her eyesight, but it stay the same if he/she stop moving.

2023-09-20 16:09 UTC, InnocentusLime commented on Assets/Scripts/Characters/PlayerBehaviour.cs
> +        Vector2 lookDirection = GetEyeSightDirection();
Update the look direction in `Update`.

2023-09-20 16:10 UTC, InnocentusLime requested changes
More or less okay. Fix the notes please and we can merge it :)

2023-09-21 08:15 UTC, alpdk commented on Assets/Scripts/Characters/PlayerBehaviour.cs
> +        }
Ok, I agree with this opinion, and I will change it.

2023-09-21 08:16 UTC, alpdk commented on Assets/Scripts/Characters/PlayerBehaviour.cs
> +        Vector2 lookDirection = GetEyeSightDirection();
Ok.

2023-09-21 08:56 UTC, InnocentusLime commented on Assets/Scripts/Characters/PlayerBehaviour.cs
> +            LookInDirection(new Vector2(Mathf.Sign(walkSpeed), 0));
There is no need to do the `Mathf.Sign` stuff. The eyesight API normalises the vector it receives

2023-09-21 09:01 UTC, InnocentusLime approved these changes

2023-09-21 09:02 UTC, InnocentusLime commented
Closes #62

2023-09-21 09:02 UTC, merged